# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 52a712d30c898b14c5d10c9ea72fa54784154d617d49fc1bdf672b194c4483c87f8b7e80fea3d52da9c0bd1f99da4b4bd462fcb6652ae962046782d99e93d15b

test:
  secret_key_base: 97ba6829069cc9c1cf045c79751c696704b6561cda522421d2f42b23ab6d78f77a24c9c0f411de12a9c816590988f85e9dcfaab3b2b0b138419b1d91c431263e

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
